version: 2.1

# required for dynamic configuration feature
setup: true

# the continuation orb: required to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

# TODO: Use only the necessary parts of the doc-only steps
# to trigger the right configuration
# Path 1: Doc Only, echo "I am docs only change"
# Path 2: Non-Doc Only, echo "I am the full build process"
step-check-for-doc-only-change: &step-check-for-doc-only-change
  run:
    name: Check if commit is doc only change
    command: |
      cd src/electron
      node script/yarn install --frozen-lockfile
      if node script/doc-only-change.js --prNumber=$CIRCLE_PR_NUMBER --prURL=$CIRCLE_PULL_REQUEST --prBranch=$CIRCLE_BRANCH; then
        #PR is doc only change; save file with value true to indicate doc only change
        echo "true" > .skip-ci-build
      else
        #PR is not a doc only change; create empty file to indicate check has been done
        touch .skip-ci-build
      fi

step-persist-doc-only-change: &step-persist-doc-only-change
  persist_to_workspace:
    root: .
    paths:
      - src/electron/.skip-ci-build

step-maybe-early-exit-doc-only-change: &step-maybe-early-exit-doc-only-change
  run:
    name: Shortcircuit build if doc only change
    command: |
      if [ -s src/electron/.skip-ci-build ]; then
        circleci-agent step halt
      fi

step-maybe-early-exit-no-doc-change: &step-maybe-early-exit-no-doc-change
  run:
    name: Shortcircuit job if change is not doc only
    command: |
      if [ ! -s src/electron/.skip-ci-build ]; then
        circleci-agent step halt
      fi

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            ./generate-config > generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup